---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-l2-w1-j11-sleep-sw-8
  namespace: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  template:
    spec:
      containers:
      - name: time-container
        # Use a minimal image with the date command available
        image: busybox
        command: ["sh", "-c", "echo The current time is: $(date); sleep 25s"]
      # Jobs must have a RestartPolicy of OnFailure or Never
      restartPolicy: Never 
  # This ensures the job runs until it completes successfully
  backoffLimit: 4 