
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-in-any-ns-app-2
  namespace: argocd
spec:
  project: app-in-any-ns-appproject
  source:
    repoURL: https://github.com/thirumurthis/argocd-app.git
    targetRevision: HEAD
    path: app-in-any-ns/my-backend-app/
  destination:
    server: https://172.19.0.5:6443  # fetched using kubectl get ep from target cluster (https://github.com/argoproj/argo-cd/issues/4204)
    namespace: env-dev-1
