---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-l1-w2-sw-14
  namespace: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  template:
    spec:
      containers:
      - name: time-container
        # Use a minimal image with the date command available
        image: busybox
        command: ["sh", "-c", "echo The current time is: $(date); sleep 30s"]
      # Jobs must have a RestartPolicy of OnFailure or Never
      restartPolicy: Never 
  # This ensures the job runs until it completes successfully
  backoffLimit: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-l1-w2-sw-15
  namespace: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  selector:
    matchLabels:
      app: nginx-app-l1-w2
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app-l1-w2
    spec:
      # Init containers run sequentially and must complete successfully before app containers start
      initContainers:
      - name: wait-for-duration
        image: busybox
        command: ["sh", "-c", "echo The current time is: $(date); sleep 15s; echo Wait complete.;"]      
      # The main application container
      containers:
      - name: nginx-app-l1-w2
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15 # Wait an additional 5 seconds after init containers finish before first probe
          periodSeconds: 10