---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-l1-w2-sw-14
  namespace: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: sleep
          image: ubuntu:latest
          command:
            - /bin/sh
            - -c
            - |
              sleep 30s
      restartPolicy: Never
  backoffLimit: 1