apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-in-any-ns-appproject
  namespace: argocd
spec:
  description: "parent argocd application project"
  destinations:
  # If namespace namespace and server not set to * currently seeing an issue when deploying argocd my-backend-application-1
  # pplication destination server 'https://172.19.0.4:6443' and namespace 'env-dev-0' 
  # do not match any of the allowed destinations in project 'app-in-any-ns-appproject'
  - namespace: '*'
    server: '*'
  # Allow manifests to deploy from any Git repos
  sourceRepos:
   - '*'
  sourceNamespaces:
   - env-*
  clusterResourceWhitelist:
   - group: '*'
     kind: '*'
 
