---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-l1-w0-sleep-sw-4
  namespace: demo-ns
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: sleep
          image: ubuntu:latest
          command:
            - /bin/sh
            - -c
            - |
              sleep 10
      restartPolicy: Never
  backoffLimit: 1