---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-l1-wave0-sw-2
  namespace: &argons demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/thirumurthis/argocd-app.git
    path: argocd_sync_wave/wave-0
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: *argons
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true