---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-l1-wave2-sw-12
  namespace: &argons argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: https://github.com/thirumurthis/argocd-app.git
    path: argocd_sync_wave/app-waves/wave-2
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: *argons
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true